import { addDaysToDateOnly, addMonthsToDateOnly, getAppTodayString } from "@/lib/date-utils";
import type { ActivityEvent, Invoice, InvoiceRepository } from "@/lib/types";

const demoToday = getAppTodayString();

function days(offset: number) {
  return addDaysToDateOnly(demoToday, offset);
}

function monthsAgo(months: number, dayOffset = 0) {
  return addDaysToDateOnly(addMonthsToDateOnly(demoToday, -months), dayOffset);
}

function invoice(input: Omit<Invoice, "balanceRemaining" | "createdAt" | "updatedAt">): Invoice {
  const balanceRemaining = Math.max(0, input.amount - input.amountPaid);
  const createdAt = `${input.invoiceDate}T09:30:00.000Z`;
  const updatedAt = `${input.invoiceDate}T16:45:00.000Z`;

  return {
    ...input,
    balanceRemaining,
    createdAt,
    updatedAt
  };
}

export const mockInvoices: Invoice[] = [
  invoice({
    id: "inv-aurora-001",
    invoiceNumber: "ARC-2026-001",
    type: "receivable",
    partyName: "Aurora Atelier Group",
    contact: "finance@aurora.example",
    invoiceDate: monthsAgo(0, -18),
    dueDate: days(-4),
    amount: 24800,
    currency: "USD",
    status: "Overdue",
    paymentMethod: "Bank transfer",
    category: "Design Retainer",
    notes: "Final payment for brand system rollout.",
    internalRemarks: "CEO requested direct follow-up if unpaid this week.",
    priority: "Critical",
    reminderDate: days(-1),
    amountPaid: 9000,
    tags: ["retainer", "brand", "priority"],
    referenceNumber: "PO-AUR-4519",
    recurring: false,
    attachmentName: "aurora-signed-sow.pdf"
  }),
  invoice({
    id: "inv-cobalt-002",
    invoiceNumber: "COB-2026-014",
    type: "payable",
    partyName: "Cobalt Cloud Systems",
    contact: "billing@cobalt.example",
    invoiceDate: monthsAgo(0, -12),
    dueDate: days(0),
    amount: 7800,
    currency: "USD",
    status: "Due Soon",
    paymentMethod: "ACH",
    category: "Cloud Infrastructure",
    notes: "Quarterly compute reserve.",
    priority: "High",
    reminderDate: days(0),
    amountPaid: 0,
    tags: ["cloud", "operations"],
    referenceNumber: "SUB-CCS-Q2",
    recurring: true
  }),
  invoice({
    id: "inv-northline-003",
    invoiceNumber: "NLM-2026-009",
    type: "receivable",
    partyName: "Northline Mobility",
    contact: "ap@northline.example",
    invoiceDate: monthsAgo(0, -9),
    dueDate: days(1),
    amount: 16450,
    currency: "USD",
    status: "Pending",
    paymentMethod: "Wire",
    category: "Implementation",
    notes: "Milestone two delivery accepted.",
    priority: "High",
    reminderDate: days(0),
    amountPaid: 0,
    tags: ["implementation", "milestone"],
    referenceNumber: "NLM-M2-226",
    recurring: false
  }),
  invoice({
    id: "inv-veridian-004",
    invoiceNumber: "VER-2026-117",
    type: "payable",
    partyName: "Veridian Legal LLP",
    contact: "invoices@veridian.example",
    invoiceDate: monthsAgo(0, -20),
    dueDate: days(-9),
    amount: 4200,
    currency: "USD",
    status: "Overdue",
    paymentMethod: "Bank transfer",
    category: "Legal",
    notes: "Contract review and compliance package.",
    priority: "Critical",
    reminderDate: days(-3),
    amountPaid: 0,
    tags: ["legal", "compliance"],
    referenceNumber: "VL-04492",
    recurring: false
  }),
  invoice({
    id: "inv-helio-005",
    invoiceNumber: "HEL-2026-058",
    type: "receivable",
    partyName: "Helio Market Labs",
    contact: "payments@heliomarket.example",
    invoiceDate: monthsAgo(1, 4),
    dueDate: days(6),
    amount: 9900,
    currency: "USD",
    status: "Due Soon",
    paymentMethod: "ACH",
    category: "Analytics",
    notes: "Monthly intelligence package.",
    priority: "Medium",
    reminderDate: days(4),
    amountPaid: 0,
    tags: ["analytics", "monthly"],
    referenceNumber: "HML-0426",
    recurring: true
  }),
  invoice({
    id: "inv-luma-006",
    invoiceNumber: "LUM-2026-033",
    type: "payable",
    partyName: "Luma Creative Studio",
    contact: "studio@luma.example",
    invoiceDate: monthsAgo(1, 9),
    dueDate: days(9),
    amount: 6250,
    currency: "USD",
    status: "Pending",
    paymentMethod: "Credit card",
    category: "Creative Production",
    notes: "Campaign image licensing and retouching.",
    priority: "Medium",
    reminderDate: days(7),
    amountPaid: 0,
    tags: ["creative", "campaign"],
    referenceNumber: "LCS-3801",
    recurring: false,
    attachmentName: "usage-rights.pdf"
  }),
  invoice({
    id: "inv-summit-007",
    invoiceNumber: "SUM-2026-221",
    type: "receivable",
    partyName: "Summit Ridge Capital",
    contact: "finance@summitridge.example",
    invoiceDate: monthsAgo(1, -2),
    dueDate: days(-16),
    amount: 37200,
    currency: "USD",
    status: "Partially Paid",
    paymentMethod: "Wire",
    category: "Advisory",
    notes: "Remaining balance pending board approval.",
    priority: "Critical",
    reminderDate: days(-7),
    amountPaid: 22000,
    tags: ["advisory", "enterprise"],
    referenceNumber: "SRC-ADV-88",
    recurring: false
  }),
  invoice({
    id: "inv-meridian-008",
    invoiceNumber: "MER-2026-019",
    type: "payable",
    partyName: "Meridian Talent Partners",
    contact: "billing@meridiantalent.example",
    invoiceDate: monthsAgo(1, 2),
    dueDate: days(13),
    amount: 12100,
    currency: "USD",
    status: "Pending",
    paymentMethod: "Bank transfer",
    category: "Recruiting",
    notes: "Placement fee for finance operations lead.",
    priority: "High",
    reminderDate: days(10),
    amountPaid: 0,
    tags: ["hiring", "operations"],
    referenceNumber: "MTP-762",
    recurring: false
  }),
  invoice({
    id: "inv-kinetic-009",
    invoiceNumber: "KIN-2026-104",
    type: "receivable",
    partyName: "Kinetic Foods Co.",
    contact: "ap@kineticfoods.example",
    invoiceDate: monthsAgo(2, 4),
    dueDate: monthsAgo(1, 3),
    amount: 18400,
    currency: "USD",
    status: "Paid",
    paymentMethod: "ACH",
    category: "Product Strategy",
    notes: "Paid within terms.",
    priority: "Medium",
    amountPaid: 18400,
    tags: ["strategy", "food"],
    referenceNumber: "KFC-Q1-29",
    recurring: false
  }),
  invoice({
    id: "inv-obsidian-010",
    invoiceNumber: "OBS-2026-002",
    type: "payable",
    partyName: "Obsidian Security",
    contact: "ar@obsidian.example",
    invoiceDate: monthsAgo(2, 1),
    dueDate: monthsAgo(1, 8),
    amount: 3300,
    currency: "USD",
    status: "Paid",
    paymentMethod: "ACH",
    category: "Security",
    notes: "Annual audit tooling.",
    priority: "Low",
    amountPaid: 3300,
    tags: ["security", "audit"],
    referenceNumber: "OBS-AUD-2026",
    recurring: true
  }),
  invoice({
    id: "inv-paloma-011",
    invoiceNumber: "PAL-2026-074",
    type: "receivable",
    partyName: "Paloma Hotels",
    contact: "finance@palomahotels.example",
    invoiceDate: monthsAgo(2, -5),
    dueDate: days(20),
    amount: 14200,
    currency: "USD",
    status: "Pending",
    paymentMethod: "Wire",
    category: "Operations Consulting",
    notes: "Guest experience systems mapping.",
    priority: "Medium",
    reminderDate: days(17),
    amountPaid: 0,
    tags: ["hospitality", "consulting"],
    referenceNumber: "PH-OPS-14",
    recurring: false
  }),
  invoice({
    id: "inv-sable-012",
    invoiceNumber: "SAB-2026-309",
    type: "payable",
    partyName: "Sable Office Services",
    contact: "billing@sableoffice.example",
    invoiceDate: monthsAgo(0, -5),
    dueDate: days(3),
    amount: 1350,
    currency: "USD",
    status: "Due Soon",
    paymentMethod: "Credit card",
    category: "Office",
    notes: "Meeting suite and mail services.",
    priority: "Low",
    reminderDate: days(2),
    amountPaid: 0,
    tags: ["office", "admin"],
    referenceNumber: "SOS-APR",
    recurring: true
  }),
  invoice({
    id: "inv-terra-013",
    invoiceNumber: "TER-2026-063",
    type: "receivable",
    partyName: "TerraGrid Energy",
    contact: "vendorpay@terragrid.example",
    invoiceDate: monthsAgo(3, 3),
    dueDate: monthsAgo(2, 10),
    amount: 26800,
    currency: "USD",
    status: "Paid",
    paymentMethod: "Wire",
    category: "Research",
    notes: "Feasibility study phase one.",
    priority: "High",
    amountPaid: 26800,
    tags: ["energy", "research"],
    referenceNumber: "TGE-FS-1",
    recurring: false
  }),
  invoice({
    id: "inv-voyage-014",
    invoiceNumber: "VOY-2026-510",
    type: "payable",
    partyName: "Voyage Travel Desk",
    contact: "billing@voyagedesk.example",
    invoiceDate: monthsAgo(3, 5),
    dueDate: monthsAgo(2, 12),
    amount: 2750,
    currency: "USD",
    status: "Paid",
    paymentMethod: "Corporate card",
    category: "Travel",
    notes: "Client workshop travel.",
    priority: "Low",
    amountPaid: 2750,
    tags: ["travel", "workshop"],
    referenceNumber: "VTD-5540",
    recurring: false
  }),
  invoice({
    id: "inv-prism-015",
    invoiceNumber: "PRI-2026-047",
    type: "receivable",
    partyName: "Prism Ventures",
    contact: "ops@prismventures.example",
    invoiceDate: monthsAgo(0, -2),
    dueDate: days(28),
    amount: 52000,
    currency: "USD",
    status: "Draft",
    paymentMethod: "Wire",
    category: "Strategic Program",
    notes: "Awaiting final purchasing details.",
    priority: "High",
    reminderDate: days(24),
    amountPaid: 0,
    tags: ["enterprise", "draft"],
    referenceNumber: "PRI-STRAT-2",
    recurring: false
  }),
  invoice({
    id: "inv-orbit-016",
    invoiceNumber: "ORB-2026-091",
    type: "payable",
    partyName: "Orbit Data Exchange",
    contact: "accounts@orbitdata.example",
    invoiceDate: monthsAgo(0, -7),
    dueDate: days(18),
    amount: 5150,
    currency: "USD",
    status: "Pending",
    paymentMethod: "ACH",
    category: "Data",
    notes: "Market feed subscription.",
    priority: "Medium",
    reminderDate: days(15),
    amountPaid: 0,
    tags: ["data", "subscription"],
    referenceNumber: "ODX-8751",
    recurring: true
  }),
  invoice({
    id: "inv-casa-017",
    invoiceNumber: "CAS-2026-018",
    type: "receivable",
    partyName: "Casa Verde Imports",
    contact: "payments@casaverde.example",
    invoiceDate: monthsAgo(4, 8),
    dueDate: monthsAgo(3, 6),
    amount: 11200,
    currency: "USD",
    status: "Paid",
    paymentMethod: "ACH",
    category: "Workflow Audit",
    notes: "Final payment received.",
    priority: "Medium",
    amountPaid: 11200,
    tags: ["audit", "workflow"],
    referenceNumber: "CVI-18",
    recurring: false
  }),
  invoice({
    id: "inv-equinox-018",
    invoiceNumber: "EQX-2026-032",
    type: "payable",
    partyName: "Equinox Finance Tools",
    contact: "billing@equinoxft.example",
    invoiceDate: monthsAgo(4, 10),
    dueDate: monthsAgo(3, 12),
    amount: 1890,
    currency: "USD",
    status: "Paid",
    paymentMethod: "Credit card",
    category: "Software",
    notes: "Controller toolkit license.",
    priority: "Low",
    amountPaid: 1890,
    tags: ["software", "finance"],
    referenceNumber: "EQX-LIC-26",
    recurring: true
  })
];

export const mockActivity: ActivityEvent[] = [
  {
    id: "act-001",
    invoiceId: "inv-northline-003",
    title: "Reminder queued",
    description: "Northline Mobility is due tomorrow. Finance contact receives a reminder today.",
    createdAt: `${days(0)}T10:00:00.000Z`,
    tone: "warning"
  },
  {
    id: "act-002",
    invoiceId: "inv-cobalt-002",
    title: "Payment deadline today",
    description: "Cobalt Cloud Systems is scheduled for ACH release.",
    createdAt: `${days(0)}T08:15:00.000Z`,
    tone: "neutral"
  },
  {
    id: "act-003",
    invoiceId: "inv-aurora-001",
    title: "Partial payment logged",
    description: "A $9,000 payment reduced the Aurora balance.",
    createdAt: `${days(-2)}T15:30:00.000Z`,
    tone: "success"
  },
  {
    id: "act-004",
    invoiceId: "inv-veridian-004",
    title: "Payable crossed terms",
    description: "Veridian Legal LLP is now nine days overdue.",
    createdAt: `${days(-1)}T12:00:00.000Z`,
    tone: "danger"
  }
];

export const mockInvoiceRepository: InvoiceRepository = {
  async listInvoices() {
    return mockInvoices;
  },
  async getInvoiceById(id) {
    return mockInvoices.find((item) => item.id === id) ?? null;
  }
};
